[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Alex C"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
fastapi = "^0.110.0"
tekore = "^5.4.0"
uvicorn = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
